#!/usr/bin/env python3
"""Compile the dashboard translation tables into a shared frontend script.

Run from the repo root after changing anything under
custom_components/casora/translations/dashboard/:

    python3 tools/build-i18n.py

Two layers:

  • Keys – window._casoraT(key, english, vars) for the Hemma core strings.
    en.json is the key reference, not a shipped table: every call site carries
    its English default inline. Only the other languages are emitted.

  • Phrases – Casora's own cards and popups are written in German. For every
    other language the rendered text is translated on the way out (button-card
    output and window.casoraTr), from phrases/<lang>.json:
        {"exact": {"<German>": "<translation>"},
         "patterns": [["^<regex on the German text>$", "… {1} …"]]}
    A language without its own table falls back to English. Text that looks
    German but has no entry is collected: casoraTrMissing() in the console.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "custom_components/casora/translations/dashboard")
PHRASES = os.path.join(SRC, "phrases")
OUT = os.path.join(ROOT, "custom_components/casora/scripts/casora-i18n.js")

RUNTIME = r"""// Generated by tools/build-i18n.py. Do not edit; edit
// custom_components/casora/translations/dashboard/ and rebuild.
(function () {
  var TABLES = %s;
  var PHRASES = %s;

  function lang() {
    var root = document.querySelector('home-assistant');
    var h = root && root.hass;
    return (h && ((h.locale && h.locale.language) || h.language)) || 'en';
  }

  var cache = { lang: null, table: null };

  function resolve() {
    var l = lang();
    if (cache.lang === l) return cache.table;
    cache.lang = l;
    cache.table = TABLES[l] || TABLES[l.split('-')[0]] || null;
    return cache.table;
  }

  function fill(s, vars) {
    if (!vars) return s;
    return s.replace(/\{(\w+)\}/g, function (m, k) {
      return Object.prototype.hasOwnProperty.call(vars, k) ? String(vars[k]) : m;
    });
  }

  window._casoraT = function (key, en, vars) {
    var t = resolve();
    var s = (t && typeof t[key] === 'string' && t[key]) || en;
    return fill(typeof s === 'string' ? s : key, vars);
  };

  window._casoraI18NLangs = Object.keys(TABLES);

  // ── Phrases: German source text → current language ───────────────────────
  // Locale for numbers and dates in Casora's own texts (was hard 'de-DE').
  window.casoraLocale = function () { return lang(); };

  var ph = { lang: null, table: null, re: [], memo: new Map(), source: false };
  var missing = new Set();
  var GERMAN = /[äöüÄÖÜß]|\b(und|oder|nicht|kein|keine|jetzt|heute|gestern|morgen|seit|noch|vor|läuft|Uhr|Tage?|Woche|Fenster|Licht|Akku|fällig|Fehler|Alle|Zuletzt|Raum|Räume|Gerät|Geräte|Aus|An|Offen|Bereit|Fertig|Pausiert|Verbrauch|Leistung|Gesamt|Restzeit|Programm|Letzte|Nächste|Keine?|Nichts|gerade|eben|bis|Min\.|Std\.|Tippen|Öffnen|Schließen|Weiter|Zurück|Neu|Starten)\b/;

  function phTable() {
    var l = lang();
    if (ph.lang === l) return ph.table;
    ph.lang = l; ph.memo = new Map();
    var base = l.split('-')[0];
    // Deutsch ist die Quellsprache; phrases/de.json übersetzt nur englische Reste
    // (z. B. die internen Abschnittsnamen „Favorites“/„Scenes“).
    ph.source = base === 'de';
    ph.table = PHRASES[l] || PHRASES[base] || (ph.source ? null : PHRASES.en) || null;
    ph.re = ((ph.table && ph.table.patterns) || []).map(function (p) {
      try { return [new RegExp(p[0]), p[1]]; } catch (e) { return null; }
    }).filter(Boolean);
    // Beim Laden meldet HA kurz die Server-Sprache, dann die des Profils: Elemente,
    // die dazwischen entstanden, jetzt nachträglich unter Beobachtung nehmen.
    if (ph.table && !ph.source && window.casoraTrRescan) setTimeout(window.casoraTrRescan, 0);
    return ph.table;
  }

  function one(core, t, depth) {
    var hit = t.exact[core];
    if (typeof hit === 'string') return hit;
    if ((depth || 0) > 2) return null;
    for (var i = 0; i < ph.re.length; i++) {
      var m = core.match(ph.re[i][0]);
      if (m) {
        return ph.re[i][1].replace(/\{(\d)\}/g, function (x, n) {
          var g = m[+n] == null ? '' : m[+n];
          // Eingebettete Teile (Namen, Zustände, „Fertig gegen …“ vor „Uhr“) ebenfalls übersetzen.
          var sub = /[A-Za-zÄÖÜäöüß]/.test(g) ? one(g, t, (depth || 0) + 1) : null;
          // Teil mit „ · “ („Heute, 14:05 · 1 Std. 5 Min.“): die Stücke einzeln wie in seg().
          if (sub === null && g.indexOf(' · ') > 0) {
            var gp = g.split(' · ');
            var gd = gp.map(function (p) { var r = /[A-Za-zÄÖÜäöüß]/.test(p) ? one(p.trim(), t, (depth || 0) + 1) : null; return r === null ? p : r; });
            if (gd.some(function (p, i) { return p !== gp[i]; })) sub = gd.join(' · ');
          }
          return sub === null ? g : sub;
        });
      }
    }
    return null;
  }

  function seg(text, t) {
    // Geschützte Leerzeichen (Uhrzeiten, Einheiten) wie normale behandeln.
    var core = text.trim().replace(/[\u00a0\u202f]/g, ' ');
    if (!core || !/[A-Za-zÄÖÜäöüß]/.test(core)) return text;
    var out = one(core, t);
    if (out === null && core.indexOf(' · ') > 0) {
      var parts = core.split(' · ');
      var done = parts.map(function (p) { var r = one(p.trim(), t); return r === null ? p : r; });
      if (done.some(function (p, i) { return p !== parts[i]; })) out = done.join(' · ');
    }
    if (out === null) {
      if (!ph.source && GERMAN.test(core) && missing.size < 3000) missing.add(core);
      return text;
    }
    var lead = text.match(/^\s*/)[0], trail = text.match(/\s*$/)[0];
    return lead + out + trail;
  }

  // Text oder HTML: nur die Textstücke zwischen den Tags werden übersetzt.
  function tr(s) {
    if (typeof s !== 'string' || !s) return s;
    var t = phTable();
    if (!t) return s;
    var hit = ph.memo.get(s);
    if (hit !== undefined) return hit;
    var out;
    if (s.indexOf('<') === -1) out = seg(s, t);
    else {
      var inStyle = false, keep = 0;
      out = s.split(/(<[^>]*>)/).map(function (p) {
        if (p.charAt(0) === '<') {
          inStyle = /^<(style|script)\b/i.test(p) || (inStyle && !/^<\/(style|script)/i.test(p));
          // <span data-no-i18n>…</span>: selbst gewählte Namen (z. B. „Home“) bleiben wörtlich.
          if (keep) { if (/^<span\b/i.test(p)) keep++; else if (/^<\/span/i.test(p)) keep--; }
          else if (/^<span\b[^>]*\bdata-no-i18n\b/i.test(p)) keep = 1;
          return p;
        }
        return inStyle || keep ? p : seg(p, t);
      }).join('');
    }
    if (ph.memo.size > 20000) ph.memo.clear();
    ph.memo.set(s, out);
    return out;
  }

  window.casoraTr = tr;
  window.casoraTrMissing = function () { return Array.from(missing).sort(); };

  // Wächter für alles, was an _unsafeHTMLorNot vorbeikommt: Popup-Titel, Live-Werte
  // per textContent, nachträglich eingesetztes HTML. Übersetzt Textknoten beim
  // Erscheinen bzw. Ändern. Nur für Zielsprachen – in der Quellsprache Deutsch
  // bleibt das DOM unangetastet (Code vergleicht teils Texte wie „Favorites“).
  var watched = new WeakSet();
  var stats = { roots: 0, skipped: 0, fixed: 0, hooks: 0 };
  window.casoraTrStats = stats;
  // Erst wenn HA seine Sprache kennt (vorher liefert lang() nur den Rückfall 'en').
  function active() {
    var root = document.querySelector('home-assistant');
    return !!(root && root.hass) && !!phTable() && !ph.source;
  }
  function fixText(n) {
    var v = n.data;
    if (!v || !/[A-Za-zÄÖÜäöüß]/.test(v)) return;
    var p = n.parentNode;
    if (p && (p.nodeName === 'STYLE' || p.nodeName === 'SCRIPT')) return;
    // Selbst gewählte Namen (z. B. Raumname „Home“) bleiben, wie sie sind.
    if (p && p.closest && p.closest('[data-no-i18n]')) return;
    var out = tr(v);
    if (out !== v) { n.data = out; stats.fixed++; }
  }
  function fixTree(node) {
    if (node.nodeType === 3) { fixText(node); return; }
    if ((node.nodeType !== 1 && node.nodeType !== 11) || node.nodeName === 'STYLE' || node.nodeName === 'SCRIPT') return;
    var w = document.createTreeWalker(node, NodeFilter.SHOW_TEXT), n;
    while ((n = w.nextNode())) fixText(n);
  }
  function watch(root) {
    if (!root || watched.has(root)) return;
    if (!active()) { stats.skipped++; return; }
    watched.add(root);
    stats.roots++;
    fixTree(root);
    new MutationObserver(function (list) {
      if (!active()) return;
      list.forEach(function (m) {
        if (m.type === 'characterData') fixText(m.target);
        else m.addedNodes.forEach(fixTree);
      });
    }).observe(root, { childList: true, subtree: true, characterData: true });
  }
  window.casoraTrWatch = watch;
  var TAGS = ['button-card', 'casora-popup', 'casora-smart-row'];
  function rescan() {
    if (!active()) return;
    (function walk(root, d) {
      if (!root || d > 30 || !root.querySelectorAll) return;
      var all = root.querySelectorAll('*');
      for (var i = 0; i < all.length; i++) {
        if (TAGS.indexOf(all[i].localName) >= 0) watch(all[i].shadowRoot);
        if (all[i].shadowRoot) walk(all[i].shadowRoot, d + 1);
      }
    })(document, 0);
  }
  window.casoraTrRescan = rescan;
  // Neue Kacheln/Popups über attachShadow erfassen. (connectedCallback am Prototyp
  // zu ersetzen wirkt nicht: der Browser merkt sich die Callbacks schon bei define.)
  if (window.Element && !Element.prototype.__casoraWatch) {
    var attach = Element.prototype.attachShadow;
    Element.prototype.attachShadow = function () {
      var root = attach.apply(this, arguments);
      if (TAGS.indexOf(this.localName) >= 0) { stats.hooks++; Promise.resolve().then(function () { watch(root); }); }
      return root;
    };
    Element.prototype.__casoraWatch = true;
  }
  rescan();  // schon vorhandene Elemente

  // Alles, was button-card als Name, Zustand, Label oder Feld zeichnet, läuft
  // durch _unsafeHTMLorNot – dort übersetzen, dann brauchen die Vorlagen nichts.
  if (window.customElements) {
    customElements.whenDefined('button-card').then(function () {
      var C = customElements.get('button-card');
      var P = C && C.prototype;
      if (!P || P.__casoraTr || typeof P._unsafeHTMLorNot !== 'function') return;
      var orig = P._unsafeHTMLorNot;
      P._unsafeHTMLorNot = function (x) {
        return orig.call(this, typeof x === 'string' ? tr(x) : x);
      };
      P.__casoraTr = true;
      // Schon gezeichnete Kacheln einmal neu zeichnen – statische Inhalte blieben
      // sonst bis zur nächsten Zustandsänderung in der Quellsprache.
      if (!phTable()) return;
      var redraw = function () {
        var out = [];
        (function walk(root, d) {
          if (!root || d > 30 || !root.querySelectorAll) return;
          var all = root.querySelectorAll('*');
          for (var i = 0; i < all.length; i++) {
            if (all[i].localName === 'button-card') out.push(all[i]);
            if (all[i].shadowRoot) walk(all[i].shadowRoot, d + 1);
          }
        })(document, 0);
        out.forEach(function (el) {
          if (typeof window.casoraKick === 'function') window.casoraKick(el);
          else if (typeof el.requestUpdate === 'function') el.requestUpdate('_config', undefined);
        });
      };
      setTimeout(redraw, 0);
      setTimeout(redraw, 2000);
    });
  }

  // Lovelace appends new resources, so this file may load either side of
  // casora-core.js. Kick whichever waiters core has already flushed.
  if (!resolve()) return;
  var w = window._casoraCoreWaiters || window._casoraKicked;
  if (!w || typeof window.casoraKick !== 'function') return;
  setTimeout(function () {
    w.forEach(function (el) { window.casoraKick(el); });
  }, 0);
})();
"""


def main() -> int:
    if not os.path.isdir(SRC):
        print("no translation source at %s" % SRC, file=sys.stderr)
        return 1

    tables = {}
    for name in sorted(os.listdir(SRC)):
        if not name.endswith(".json") or name == "en.json":
            continue
        lang = name[: -len(".json")]
        with open(os.path.join(SRC, name), encoding="utf-8") as fh:
            data = json.load(fh)
        tables[lang] = {k: v for k, v in sorted(data.items()) if isinstance(v, str)}

    phrases = {}
    if os.path.isdir(PHRASES):
        for name in sorted(os.listdir(PHRASES)):
            if not name.endswith(".json"):
                continue
            with open(os.path.join(PHRASES, name), encoding="utf-8") as fh:
                data = json.load(fh)
            bad = [p for p in data.get("patterns") or [] if not (isinstance(p, list) and len(p) == 2)]
            if bad:
                # Nicht still verwerfen: zwei verschmolzene Muster gingen sonst unbemerkt verloren.
                raise SystemExit("%s: Muster muss [Regex, Text] sein: %s" % (name, json.dumps(bad[0], ensure_ascii=False)))
            phrases[name[: -len(".json")]] = {
                "exact": {k: v for k, v in sorted((data.get("exact") or {}).items()) if isinstance(v, str)},
                "patterns": data.get("patterns") or [],
            }

    body = json.dumps(tables, ensure_ascii=False, indent=2, sort_keys=True)
    pbody = json.dumps(phrases, ensure_ascii=False, separators=(",", ":"))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(RUNTIME % (body, pbody))

    print("wrote %s (%d key table(s): %s; phrases: %s)" % (
        os.path.relpath(OUT, ROOT), len(tables), ", ".join(tables) or "none",
        ", ".join("%s %d+%d" % (k, len(v["exact"]), len(v["patterns"])) for k, v in phrases.items()) or "none"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
